const { getPeople } = require('./service')

async function main(){
    try{
        
    }
    catch(err){
        console.error(`Internal Error: `, err)
    }
}

main()